### ISSUE TITLE
please make keyboard support working in pure EFI mode

### ISSUE THREAD

**Issue by fezie** [martinwhitaker/pcmemtest#13]
Issue #2 was closed because it's documented that keyboard only works with enabled CMS aka legacy boot.

But more and more EFI systems don't ship a CSM. 
So it would be really nice if you could get the keyboard working on pure EFI systems.
Unfortunately grub2 is GPL3+ whereas pcmemtest is only GPL2. It has a working keyboard driver for pure EFI mode.

**Comment by martinwhitaker** [comment]
Just to clarify, what's required for a working USB keyboard is that the BIOS supports USB legacy keyboard emulation. On my machine with an ASUS motherboard, this is achieved by enabling the CSM in the BIOS. It then works regardless of whether you boot in UEFI or legacy mode. On another machine, which has a Gigabyte motherboard, there is a separate control in the BIOS for enabling USB legacy keyboard emulation, but on that machine it only works if you boot in legacy mode.

By default GRUB2 uses the UEFI boot services for keyboard input. That is the route PassMark went down with the proprietary Memtest86. However, apart from the technical challenge of reworking PCMemTest to be a UEFI application, there are two disadvantages to going down that route:

-  the UEFI loader and boot services use a significant amount of memory (between 100 and 200 MB on the machines I've tested). This memory has to be excluded from the memory tests, reducing the test coverage.
- the base UEFI specification only allows UEFI applications to operate in uniprocessor mode. Only BIOSs that also implement the relevant parts of the UEFI PI specification provide support for SMP.

GRUB2 does also have its own USB drivers, which can be used for keyboard input, but does not currently support XHCI controllers, which means that only works on older hardware.

PCMemTest is GPLv2 because it is derived from Memtest86+. I can't change the license, so can't copy USB drivers from other sources.

I am working on implementing USB keyboard support, but as I said in issue #2, this is not a simple task, so is going to take some time.

**Comment by fezie** [comment]
thanks for your explanation

**Comment by martinwhitaker** [comment]
There is now support for USB keyboards. It works on all my hardware, but other testers have reported problems on some platforms.

PCMemTest is now the basis for developing Memtest86+ v6.0. All future development will take place at https://github.com/memtest86plus/memtest86plus, so closing this issue.
