### ISSUE TITLE
Serial console support

### ISSUE THREAD

**Issue by cloakage** [martinwhitaker/pcmemtest#15]
If I may humbly suggest supporting serial consoles.  This would offer a method of user input, and I expect much easier than a USB keyboard driver.  It also offers an output method for headless machines, particularly servers with IPMI serial-over-LAN.

memtest86+ supports this with the typical Linux kernel option "console".  e.g. To output to both the regular console and the second serial port (at max speed), add to the boot command-line:  console=tty0 console=ttyS1,115200

Once supporting boot-time command-line options to enable a serial console, you might consider allowing other options to be set there as well, e.g. enabling SMP, without needing any user input.

**Comment by martinwhitaker** [comment]
Consumer (desktop/laptop) PCs haven't included serial ports for many years now, so this is not a viable alternative to a USB keyboard driver. Yes, it might be useful for headless machines, but server-class machines usually come with better built-in memory tests, so have less need for a standalone memory tester. So this has lower priority than adding support for USB keyboards.

It would also require the hardware to support the legacy serial port interface (using the x86 I/O instructions). I've no idea whether that is or isn't the case on servers with IPMI serial-over-LAN.

**Comment by lvd2** [comment]
When there is no serial port on motherboard, one can still use a pci-e serial port card. Most of such cards are 16550-compatible and could be used once the base address (of eight 8bit IO ports) is known. Since the pci bar addresses are set by bios and usually the same way every bootup, one can look up base address in linux (cat /sys/class/tty/ttyS*/port) and pass that as a kernel option to the test. In almost the same way (config file entry) grub is able to dump its screen over 16550-compatible pci-e serial card.

**Comment by martinwhitaker** [comment]
PCMemTest is now the basis for developing Memtest86+ v6.0. All future development will take place at https://github.com/memtest86plus/memtest86plus, so closing this issue. There is already an enhancement request there for serial console support.
